/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;





/**
 *
 * @author rohan
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }
int id=0;
int getId(){
    ResultSet rs=null;
   try{
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url="jdbc:mysql://localhost:3306/csfms?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con=DriverManager.getConnection(url,"root","rohan@123");
        String sql ="select max(id) from signup";
        java.sql.Statement st= con.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            id++;
           //id = getInt(1);
        }
   }
   catch(Exception e)
   {
       e.printStackTrace();
       
   }
   return id;

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcnumber = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        btnsignup = new javax.swing.JButton();
        txtcpfield = new javax.swing.JPasswordField();
        txtpfield = new javax.swing.JPasswordField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnclear = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        lblcpassworderror = new javax.swing.JLabel();
        lblcnumbererror = new javax.swing.JLabel();
        lblpassworderror1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Contact Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 0));
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 0));
        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        txtcnumber.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtcnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnumberActionPerformed(evt);
            }
        });
        txtcnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 230, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 270, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 270, -1));

        txtuname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 270, -1));

        btnsignup.setBackground(new java.awt.Color(242, 242, 242));
        btnsignup.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        txtcpfield.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(txtcpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 220, -1));

        txtpfield.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpfieldActionPerformed(evt);
            }
        });
        txtpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txtpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 260, -1));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 170, 30));

        btnclear.setBackground(new java.awt.Color(242, 242, 242));
        btnclear.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        btnlogin.setBackground(new java.awt.Color(242, 242, 242));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        lblcpassworderror.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblcpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 160, 20));

        lblcnumbererror.setForeground(new java.awt.Color(255, 51, 51));
        lblcnumbererror.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblcnumbererrorKeyPressed(evt);
            }
        });
        getContentPane().add(lblcnumbererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 160, 20));

        lblpassworderror1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblpassworderror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 160, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
validation();
if(validation()){
    insertData();
    
}
else
{
    JOptionPane.showMessageDialog(this,"validation issue");
}
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldActionPerformed

    private void txtpfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyPressed
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyPressed

    private void txtpfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyReleased
 passwordCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyReleased

    private void txtpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyTyped
 passwordCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyTyped

    private void lblcnumbererrorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblcnumbererrorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcnumbererrorKeyPressed

    private void txtcnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyPressed
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberKeyPressed

    private void txtcnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyReleased
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberKeyReleased

    private void txtcnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyTyped
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberKeyTyped

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
Login l1= new Login();
l1.show();
this.dispose();
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
    txtfname.setText("");
        txtlname.setText("");
        txtuname.setText("");
        txtpfield.setText("");
        txtcpfield.setText("");
        
//        txtdob.getDate();
        txtcnumber.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed
String fname,lname,uname,password,cpassword,mnumber;
Date dob;

void insertData() {
    try {
        // ✅ Get date from JDateChooser
        java.util.Date dobDate = txtdob.getDate(); // 'txtdob' is your JDateChooser
        if (dobDate == null) {
            JOptionPane.showMessageDialog(this, "Please select Date of Birth!");
            return;
        }

        // ✅ Convert java.util.Date → java.sql.Date for MySQL
        java.sql.Date sqlDate = new java.sql.Date(dobDate.getTime());

        // ✅ Load MySQL driver and connect
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/csfms?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con = DriverManager.getConnection(url, "root", "rohan@123");

        // ✅ Use PreparedStatement safely
        String sql = "INSERT INTO signup VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement st = con.prepareStatement(sql);

        // ✅ Set all parameter values
        st.setInt(1, getId());
        st.setString(2, txtfname.getText());
        st.setString(3, txtlname.getText());
        st.setString(4, txtuname.getText());
        st.setString(5, txtpfield.getText());
        st.setDate(6, sqlDate); // important — date in proper format
        st.setString(7, txtcnumber.getText());

        // ✅ Execute update
        int i = st.executeUpdate();
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Record inserted successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Record not inserted!");
        }

        // ✅ Close connection
        con.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    boolean validation()
    {
        
        fname=txtfname.getText();
        lname=txtlname.getText();
        uname=txtuname.getText();
        password=txtpfield.getText();
        cpassword=txtcpfield.getText();
        
        dob=txtdob.getDate();
        mnumber=txtcnumber.getText();
        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter First name....");
          return false;  
        }
        if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter last name....");
          return false;  
        }
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter user name....");
          return false;  
        }
        if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter password....");
          return false;  
        }
        if(cpassword.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter Conform Password....");
          return false;  
        }
        if(dob.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter Date of birth ....");
          return false;  
        }
        if(mnumber.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please Enter Mobile number ....");
          return false;  
        }
        
        return true;
        
    } 
    void passwordCheck()
    {
        password=txtpfield.getText();
        if(password.length()>=8)
        {
            lblpassworderror1.setText(" ");  
        }
        else
        {
          lblpassworderror1.setText("Enter 8 Digit Password.");  
        }
        
    }
    void mobileCheck()
    {
        mnumber=txtcnumber.getText();
       if(mnumber.length()==10)
       {
          lblcnumbererror.setText(""); 
       }
       else
       {
          lblcnumbererror.setText("Enter 10 digit mobile number") ;
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcnumbererror;
    private javax.swing.JLabel lblcpassworderror;
    private javax.swing.JLabel lblpassworderror1;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JPasswordField txtcpfield;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpfield;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
